# Generated by Django 4.2.2 on 2023-06-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Fecha completada')),
                ('evaluation', models.TextField(blank=True, null=True, verbose_name='Evaluación')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.activitie', verbose_name='Actividad')),
                ('master_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_plan.masterplan', verbose_name='Master plan')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.responsible', verbose_name='Responsable')),
                ('work_axe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.workaxe', verbose_name='Eje de trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='work_axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.workaxe', verbose_name='Eje de trabajo'),
        ),
    ]
