# Generated by Django 4.2.2 on 2023-06-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='work_axe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_made', models.DateField(blank=True)),
                ('evaluation', models.CharField(blank=True, max_length=75)),
                ('observations', models.TextField(blank=True)),
                ('activitie', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.activitie')),
                ('responsible', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.responsible')),
            ],
        ),
        migrations.AddField(
            model_name='activitie',
            name='work_axe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.work_axe'),
        ),
    ]
