# Generated by Django 4.2.2 on 2023-06-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0002_alter_date_date_made_alter_date_evaluation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='work_axe',
            new_name='WorkAxe',
        ),
    ]
