# Generated by Django 4.2.2 on 2023-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0002_alter_customuser_role_alter_detail_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
