# Generated by Django 4.2.2 on 2023-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0005_detail_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsible',
        ),
    ]
