# Generated by Django 4.2.2 on 2023-06-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0005_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='schude_date',
            new_name='scheduled_date',
        ),
    ]
