# Generated by Django 4.2.2 on 2023-06-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0006_delete_responsible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkAxe',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='activitie',
            old_name='work_axe',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='work_axe',
            new_name='component',
        ),
    ]
