# Generated by Django 4.2.2 on 2023-06-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0006_rename_schude_date_detail_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activitie',
            name='work_axe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.workaxe', verbose_name='Eje de trabajo'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.activitie', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='completed_date',
            field=models.DateField(verbose_name='Fecha completada'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='evaluation',
            field=models.TextField(blank=True, null=True, verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='master_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_plan.masterplan', verbose_name='Master plan'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='observations',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='responsible',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.responsible', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='scheduled_date',
            field=models.DateField(verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='work_axe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='master_plan.workaxe', verbose_name='Eje de trabajo'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='workaxe',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
    ]
