# Generated by Django 4.2.2 on 2023-06-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0007_alter_activitie_name_alter_activitie_work_axe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='work_axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.workaxe', verbose_name='Eje de trabajo'),
        ),
        migrations.AlterField(
            model_name='date',
            name='activitie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.activitie'),
        ),
        migrations.AlterField(
            model_name='date',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.responsible'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.activitie', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.responsible', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='work_axe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.workaxe', verbose_name='Eje de trabajo'),
        ),
    ]
