# Generated by Django 4.2.2 on 2023-06-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0008_alter_activitie_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_plan.component', verbose_name='Componente'),
        ),
    ]
