# Generated by Django 4.2.2 on 2023-06-30 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0009_alter_detail_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='responsible',
        ),
        migrations.AddField(
            model_name='detail',
            name='activity_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_manager_relation', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actividad'),
        ),
        migrations.AddField(
            model_name='detail',
            name='expected_results',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Resultados esperados'),
        ),
        migrations.AddField(
            model_name='detail',
            name='goal',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Metas'),
        ),
        migrations.AddField(
            model_name='detail',
            name='goal_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_manager_relation', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de objetivo'),
        ),
        migrations.AddField(
            model_name='detail',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='Objectivos'),
        ),
        migrations.AddField(
            model_name='detail',
            name='quantities',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidades'),
        ),
        migrations.AddField(
            model_name='detail',
            name='supervision_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_manager_relation', to=settings.AUTH_USER_MODEL, verbose_name='Responsable supervisión'),
        ),
        migrations.AddField(
            model_name='detail',
            name='tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Tareas'),
        ),
        migrations.AddField(
            model_name='detail',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='detail',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario'),
        ),
    ]
