# Generated by Django 4.2.2 on 2023-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_plan', '0010_remove_detail_responsible_detail_activity_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='name',
            field=models.TextField(unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='masterplan',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Nombre'),
        ),
    ]
